ssh_user: ENC[AES256_GCM,data:dEUqPQ==,iv:6DwIBaH5p6JV8XH8YjldQzGjAaPFS48SmRIjvyXNfbE=,tag:QikUdkrq48idbuMmHfMJ0A==,type:str]
ssh_host_public_key: ENC[AES256_GCM,data:p5G+QjQbav4HvT8zz38IldygD3htBBW1pAcl9DOs4Bp1DLvMM7MbGuQLudiVTZqd3XEC5b5bsEhq8tSe3zqQRZdXT+8SGIhIcU45ZoTxSy2da181wxnoSWsG2taFqq8/DOZo4YHE1YA=,iv:cukPIX3VkXPVeSMrJx2jXKjCcfucVmMecU8Yze2GMsY=,tag:mlBk8UyEEuw7I5IILWFzQw==,type:str]
become_pass: ENC[AES256_GCM,data:RRNDN8Lig9msOP8=,iv:bLICN2E2uOml2W3cA330CUqvWdNMalVu1W4IWKFTSxg=,tag:ziphbvOZov0C//fT807v+Q==,type:str]
token: ENC[AES256_GCM,data:R4gUNu0hRZeqre3v4iMekH02GU9FBLkBb2NY,iv:ezM2DmQqrnktOFI8cTjK8R1EO0YHyrcL/vIRlm5qVH8=,tag:wGszJ3WFb6bTJYbhMCysYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-29T07:45:27Z"
    mac: ENC[AES256_GCM,data:npA6C9gE0EELARZ5w3z3qUtWptkqbSTmiKWD83pk7x/ICg8xTx7rIoxDVK5Y0jhBKZE3RMJmEwVkRcsnVundcT+4925yosilCANFldNPxZUAjK9j5ER9o2XipXs74ruqFLubJKDCTKU9/c+syaGKcfI4uLWnrMsSJXQdMcxqOps=,iv:mTtw8XgSYzPmvfJuiH4c1BWlyY7p+Yu12c6c5p5Nkrs=,tag:J4N+qKR4nrvWicOmvfLkMQ==,type:str]
    pgp:
        - created_at: "2024-02-18T11:28:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D9e7wD6U/LL0SAQdAO5MPc50WMwOSiAPBlL2Q8q4Po4r++vCystUZs1oeJDYw
            o2r3RqTvFEHTM7Lb3kaiBZl7VYrDA/uVEmoi44hposEFtqATnCk/nB8oEYitFJ7T
            1GgBCQIQqw1DwK3DM7Y97bsx1fFmrBgtOjIErsARg3h/VZL6LIHpPSAX8hja2QVN
            yH9XBOvAlvmhz0aye3JTAx0omVLCjdePQqcaIJGPmoWhGHpoatS9L3MrRjcG8lwv
            cL1tr+ULT/AC8Q==
            =QA3H
            -----END PGP MESSAGE-----
          fp: 958F405C084066F13C37E9D7558C1B7B50D14435
    unencrypted_suffix: _unencrypted
    version: 3.8.1
