---
- name: Create the namespace for Crossplane
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    kind: Namespace
    name: "{{ crossplane_namespace }}"
    state: present

- name: Add the Crossplane Helm repository
  community.kubernetes.helm_repository:
    name: crossplane-stable
    repo_url: "https://charts.crossplane.io/stable"
    state: present

- name: Update Helm repository to ensure we get the latest list of charts
  ansible.builtin.command: helm repo update

- name: Install Crossplane using Helm
  community.kubernetes.helm:
    kubeconfig_path: "{{ kubeconfig }}"
    name: crossplane
    chart_ref: "{{ crossplane_chart }}"
    release_namespace: "{{ crossplane_namespace }}"
    chart_version: "{{ crossplane_version }}"
    state: present
    wait: yes
    values:
      replicas: 1

# Providers
- name: Apply Crossplane Providers
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    context: "default"
    state: present
    definition: "{{ lookup('template', item) }}"
  loop: "{{ query('fileglob', '../templates/providers/*.yml.j2') }}"

# HELM - ProviderConfig
- name: Check for the existence of Helm ProviderConfig CRD before continuing
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: providerconfigs.helm.crossplane.io
  register: crd_check
  until: crd_check.resources | length > 0
  retries: 20
  delay: 10

- name: Configure the Helm provider in Crossplane
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: 
      apiVersion: helm.crossplane.io/v1beta1
      kind: ProviderConfig
      metadata:
        name: provider-helm
      spec:
        credentials:
          source: InjectedIdentity

# Azure - ProviderConfig
- name: Check for the existence of Azure ProviderConfig CRD before continuing
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: providerconfigs.azure.upbound.io
  register: crd_check
  until: crd_check.resources | length > 0
  retries: 20
  delay: 10

- name: Configure the Azure provider in Crossplane
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: 
      apiVersion: azure.upbound.io/v1beta1
      metadata:
        name: provider-azure
      kind: ProviderConfig
      spec:
        credentials:
          source: Secret
          secretRef:
            namespace: crossplane-system
            name: azure-secret
            key: creds
